source 'https://rubygems.org'

ruby '2.1.2'
gem 'dashing', '~> 1.3.4'
gem 'httparty'
gem 'json'
gem 'roo'
gem 'passenger'
gem 'warden'
#gem  'dm-mysql-adapter'
gem 'dm-postgres-adapter'
gem 'data_mapper'
gem 'compass'
gem 'font_assets'
gem 'newrelic_rpm'
#gem "pg"
#gem 'dm-sqlite-adapter', '1.2.0'
#gem  'omniauth-twitter'
# gem 'bootstrap-sass', '~> 3.1.0.2'
# gem 'sass-rails', '>= 3.2'
# gem 'autoprefixer-rails'
# gem 'rails'
# gem 'compass'
# gem 'haml'
# gem 'sinatra-support'
# gem 'sprockets-helpers'
# gem 'sprockets-sass'
# gem 'uglifier'
# gem 'sprockets-rails'